# Generated by Django 3.2 on 2021-05-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('Github', models.URLField()),
                ('Linkdein', models.URLField()),
                ('Youtube', models.URLField()),
                ('MyMainimage', models.ImageField(upload_to='pics')),
                ('Myimage', models.ImageField(upload_to='pics')),
                ('Backgroundimage', models.ImageField(upload_to='pics')),
                ('Quote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('CenterName', models.CharField(max_length=100)),
                ('RankType', models.CharField(max_length=100)),
                ('Status', models.BooleanField()),
                ('Rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('joinDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Organization', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('Technology1', models.CharField(max_length=100)),
                ('Technology2', models.CharField(max_length=100)),
                ('Technology3', models.CharField(max_length=100)),
                ('ProjectLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MyResume', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=100)),
                ('Rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SoftwareName', models.CharField(max_length=100)),
                ('Softwareimage', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
