# Generated by Django 3.2 on 2021-05-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='Backgroundimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='MyMainimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='Myimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='MyResume',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='softwares',
            name='Softwareimage',
            field=models.URLField(),
        ),
    ]
