# Generated by Django 3.2 on 2021-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_auto_20210525_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
