# Generated by Django 3.2 on 2021-06-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_auto_20210602_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skillquote1', models.CharField(max_length=100)),
                ('Skillquote2', models.CharField(max_length=100)),
                ('Softquote1', models.CharField(max_length=100)),
                ('Softquote2', models.CharField(max_length=100)),
                ('Tagquote1', models.CharField(max_length=100)),
                ('Tagquote2', models.CharField(max_length=100)),
                ('Tagquote3', models.CharField(max_length=100)),
                ('Featurepic', models.ImageField(upload_to='pic')),
                ('Tagpic', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='Backgroundimage',
            new_name='Aboutpic',
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='MyMainimage',
            new_name='Bannerpic',
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='Quote',
            new_name='CurrentStatus',
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='Myimage',
            new_name='Profilepic',
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='AboutPicDesc',
            field=models.CharField(default='Title Decription', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='AboutPicTitle',
            field=models.CharField(default='TitlePic', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='AboutTitle',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='Proffesion1',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='Proffesion2',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='Proffesion3',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='Proffesion4',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='Colour',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='experiences',
            name='Colour',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
