# Generated by Django 3.2 on 2021-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_auto_20210604_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skillquote1', models.CharField(max_length=100)),
                ('Skillquote2', models.CharField(max_length=100)),
                ('Softquote1', models.CharField(max_length=100)),
                ('Softquote2', models.CharField(max_length=100)),
                ('Tagquote1', models.CharField(max_length=100)),
                ('Tagquote2', models.CharField(max_length=100)),
                ('Tagquote3', models.CharField(max_length=100)),
                ('Featurepic', models.ImageField(upload_to='pic')),
                ('Tagpic', models.ImageField(upload_to='pic')),
                ('Bannerbackground', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='OtherDetails',
        ),
    ]
