# Generated by Django 3.2 on 2021-06-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0008_auto_20210604_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetail',
            name='Bannerbackground',
            field=models.FileField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='Featurepic',
            field=models.FileField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='Tagpic',
            field=models.FileField(upload_to='pic'),
        ),
    ]
