# Generated by Django 3.2 on 2021-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_auto_20210604_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Discription',
            field=models.TextField(default='Discription'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='AboutPicDesc',
            field=models.TextField(default='Title Decription'),
        ),
    ]
